/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AverageSoilParameters {
  'avgNkgPerBed' : number,
  'avgNitrogen' : number,
  'avgCu' : number,
  'avgEc' : number,
  'avgFe' : number,
  'avgMn' : number,
  'avgOc' : number,
  'avgOm' : number,
  'avgPh' : number,
  'avgZn' : number,
  'avgCalcium' : number,
  'avgSodium' : number,
  'avgPotassium' : number,
  'avgKkgPerBed' : number,
  'avgPkgPerBed' : number,
  'avgPhosphorus' : number,
  'avgSulfur' : number,
  'avgMagnesium' : number,
  'avgCec' : number,
}
export interface ComprehensiveSoilHealthCard {
  'status' : string,
  'averages' : AverageSoilParameters,
  'afterMeasurement' : [] | [SoilMeasurement],
  'parameterComparisons' : ParameterComparisonCard,
  'recentMeasurements' : Array<SoilMeasurement>,
  'overallComparison' : ParameterComparison,
  'beforeMeasurement' : [] | [SoilMeasurement],
  'analysis' : TrendAnalysis,
  'referenceMeasurement' : [] | [SoilMeasurement],
}
export type MeasurementType = { 'after' : null } |
  { 'reference' : null } |
  { 'before' : null } |
  { 'daily' : null };
export interface ParameterComparison {
  'trend' : string,
  'after' : number,
  'difference' : number,
  'percentageChange' : number,
  'before' : number,
}
export interface ParameterComparisonCard {
  'nitrogenComparison' : ParameterComparison,
  'feComparison' : ParameterComparison,
  'phComparison' : ParameterComparison,
  'magnesiumComparison' : ParameterComparison,
  'kKgPerBedComparison' : ParameterComparison,
  'nKgPerBedComparison' : ParameterComparison,
  'pKgPerBedComparison' : ParameterComparison,
  'cuComparison' : ParameterComparison,
  'ocComparison' : ParameterComparison,
  'mnComparison' : ParameterComparison,
  'omComparison' : ParameterComparison,
  'sodiumComparison' : ParameterComparison,
  'znComparison' : ParameterComparison,
  'phosphorusComparison' : ParameterComparison,
  'cecComparison' : ParameterComparison,
  'ecComparison' : ParameterComparison,
  'calciumComparison' : ParameterComparison,
  'potassiumComparison' : ParameterComparison,
  'sulfurComparison' : ParameterComparison,
}
export interface SoilMeasurement {
  'cu' : number,
  'ec' : number,
  'fe' : number,
  'mn' : number,
  'oc' : number,
  'om' : number,
  'ph' : number,
  'zn' : number,
  'cec' : number,
  'kKgPerBed' : number,
  'soilType' : [] | [string],
  'sodium' : number,
  'pKgPerBed' : number,
  'potassium' : number,
  'phosphorus' : number,
  'date' : Time,
  'calcium' : number,
  'referenceId' : [] | [bigint],
  'nKgPerBed' : number,
  'notes' : [] | [string],
  'sulfur' : number,
  'magnesium' : number,
  'measurementType' : MeasurementType,
  'location' : [] | [string],
  'nitrogen' : number,
}
export type Time = bigint;
export interface TrendAnalysis {
  'kKgPerBedTrend' : string,
  'phosphorusTrend' : string,
  'totalNutrientTrend' : string,
  'omTrend' : string,
  'ocTrend' : string,
  'mnTrend' : string,
  'sodiumTrend' : string,
  'nKgPerBedTrend' : string,
  'phTrend' : string,
  'znTrend' : string,
  'magnesiumTrend' : string,
  'nitrogenTrend' : string,
  'cuTrend' : string,
  'feTrend' : string,
  'ecTrend' : string,
  'calciumTrend' : string,
  'cecTrend' : string,
  'sulfurTrend' : string,
  'potassiumTrend' : string,
  'pKgPerBedTrend' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSoilMeasurement' : ActorMethod<
    [
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      MeasurementType,
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
      Time,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUserMeasurements' : ActorMethod<[], Array<SoilMeasurement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComprehensiveSoilHealthCard' : ActorMethod<
    [],
    [] | [ComprehensiveSoilHealthCard]
  >,
  'getMeasurementsByLocation' : ActorMethod<[string], Array<SoilMeasurement>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];