/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface ParameterComparison {
    trend: string;
    after: number;
    difference: number;
    percentageChange: number;
    before: number;
}
export interface TrendAnalysis {
    kKgPerBedTrend: string;
    phosphorusTrend: string;
    totalNutrientTrend: string;
    omTrend: string;
    ocTrend: string;
    mnTrend: string;
    sodiumTrend: string;
    nKgPerBedTrend: string;
    phTrend: string;
    znTrend: string;
    magnesiumTrend: string;
    nitrogenTrend: string;
    cuTrend: string;
    feTrend: string;
    ecTrend: string;
    calciumTrend: string;
    cecTrend: string;
    sulfurTrend: string;
    potassiumTrend: string;
    pKgPerBedTrend: string;
}
export interface ComprehensiveSoilHealthCard {
    status: string;
    averages: AverageSoilParameters;
    afterMeasurement?: SoilMeasurement;
    parameterComparisons: ParameterComparisonCard;
    recentMeasurements: Array<SoilMeasurement>;
    overallComparison: ParameterComparison;
    beforeMeasurement?: SoilMeasurement;
    analysis: TrendAnalysis;
    referenceMeasurement?: SoilMeasurement;
}
export interface SoilMeasurement {
    cu: number;
    ec: number;
    fe: number;
    mn: number;
    oc: number;
    om: number;
    ph: number;
    zn: number;
    cec: number;
    kKgPerBed: number;
    soilType?: string;
    sodium: number;
    pKgPerBed: number;
    potassium: number;
    phosphorus: number;
    date: Time;
    calcium: number;
    referenceId?: bigint;
    nKgPerBed: number;
    notes?: string;
    sulfur: number;
    magnesium: number;
    measurementType: MeasurementType;
    location?: string;
    nitrogen: number;
}
export interface ParameterComparisonCard {
    nitrogenComparison: ParameterComparison;
    feComparison: ParameterComparison;
    phComparison: ParameterComparison;
    magnesiumComparison: ParameterComparison;
    kKgPerBedComparison: ParameterComparison;
    nKgPerBedComparison: ParameterComparison;
    pKgPerBedComparison: ParameterComparison;
    cuComparison: ParameterComparison;
    ocComparison: ParameterComparison;
    mnComparison: ParameterComparison;
    omComparison: ParameterComparison;
    sodiumComparison: ParameterComparison;
    znComparison: ParameterComparison;
    phosphorusComparison: ParameterComparison;
    cecComparison: ParameterComparison;
    ecComparison: ParameterComparison;
    calciumComparison: ParameterComparison;
    potassiumComparison: ParameterComparison;
    sulfurComparison: ParameterComparison;
}
export interface UserProfile {
    name: string;
}
export interface AverageSoilParameters {
    avgNkgPerBed: number;
    avgNitrogen: number;
    avgCu: number;
    avgEc: number;
    avgFe: number;
    avgMn: number;
    avgOc: number;
    avgOm: number;
    avgPh: number;
    avgZn: number;
    avgCalcium: number;
    avgSodium: number;
    avgPotassium: number;
    avgKkgPerBed: number;
    avgPkgPerBed: number;
    avgPhosphorus: number;
    avgSulfur: number;
    avgMagnesium: number;
    avgCec: number;
}
export enum MeasurementType {
    after = "after",
    reference = "reference",
    before = "before",
    daily = "daily"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSoilMeasurement(ph: number, ec: number, oc: number, om: number, nitrogen: number, phosphorus: number, potassium: number, sulfur: number, calcium: number, magnesium: number, sodium: number, fe: number, mn: number, zn: number, cu: number, cec: number, nKgPerBed: number, pKgPerBed: number, kKgPerBed: number, measurementType: MeasurementType, notes: string | null, referenceId: bigint | null, location: string | null, soilType: string | null, date: Time): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllUserMeasurements(): Promise<Array<SoilMeasurement>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComprehensiveSoilHealthCard(): Promise<ComprehensiveSoilHealthCard | null>;
    getMeasurementsByLocation(location: string): Promise<Array<SoilMeasurement>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { AverageSoilParameters as _AverageSoilParameters, ComprehensiveSoilHealthCard as _ComprehensiveSoilHealthCard, MeasurementType as _MeasurementType, ParameterComparison as _ParameterComparison, ParameterComparisonCard as _ParameterComparisonCard, SoilMeasurement as _SoilMeasurement, Time as _Time, TrendAnalysis as _TrendAnalysis, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSoilMeasurement(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number, arg8: number, arg9: number, arg10: number, arg11: number, arg12: number, arg13: number, arg14: number, arg15: number, arg16: number, arg17: number, arg18: number, arg19: MeasurementType, arg20: string | null, arg21: bigint | null, arg22: string | null, arg23: string | null, arg24: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSoilMeasurement(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, to_candid_MeasurementType_n1(this._uploadFile, this._downloadFile, arg19), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg22), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg23), arg24);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSoilMeasurement(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, to_candid_MeasurementType_n1(this._uploadFile, this._downloadFile, arg19), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg22), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg23), arg24);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllUserMeasurements(): Promise<Array<SoilMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserMeasurements();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserMeasurements();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComprehensiveSoilHealthCard(): Promise<ComprehensiveSoilHealthCard | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getComprehensiveSoilHealthCard();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComprehensiveSoilHealthCard();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeasurementsByLocation(arg0: string): Promise<Array<SoilMeasurement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeasurementsByLocation(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeasurementsByLocation(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_ComprehensiveSoilHealthCard_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ComprehensiveSoilHealthCard): ComprehensiveSoilHealthCard {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_MeasurementType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MeasurementType): MeasurementType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SoilMeasurement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoilMeasurement): SoilMeasurement {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ComprehensiveSoilHealthCard]): ComprehensiveSoilHealthCard | null {
    return value.length === 0 ? null : from_candid_ComprehensiveSoilHealthCard_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SoilMeasurement]): SoilMeasurement | null {
    return value.length === 0 ? null : from_candid_SoilMeasurement_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    averages: _AverageSoilParameters;
    afterMeasurement: [] | [_SoilMeasurement];
    parameterComparisons: _ParameterComparisonCard;
    recentMeasurements: Array<_SoilMeasurement>;
    overallComparison: _ParameterComparison;
    beforeMeasurement: [] | [_SoilMeasurement];
    analysis: _TrendAnalysis;
    referenceMeasurement: [] | [_SoilMeasurement];
}): {
    status: string;
    averages: AverageSoilParameters;
    afterMeasurement?: SoilMeasurement;
    parameterComparisons: ParameterComparisonCard;
    recentMeasurements: Array<SoilMeasurement>;
    overallComparison: ParameterComparison;
    beforeMeasurement?: SoilMeasurement;
    analysis: TrendAnalysis;
    referenceMeasurement?: SoilMeasurement;
} {
    return {
        status: value.status,
        averages: value.averages,
        afterMeasurement: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.afterMeasurement)),
        parameterComparisons: value.parameterComparisons,
        recentMeasurements: from_candid_vec_n7(_uploadFile, _downloadFile, value.recentMeasurements),
        overallComparison: value.overallComparison,
        beforeMeasurement: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.beforeMeasurement)),
        analysis: value.analysis,
        referenceMeasurement: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.referenceMeasurement))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cu: number;
    ec: number;
    fe: number;
    mn: number;
    oc: number;
    om: number;
    ph: number;
    zn: number;
    cec: number;
    kKgPerBed: number;
    soilType: [] | [string];
    sodium: number;
    pKgPerBed: number;
    potassium: number;
    phosphorus: number;
    date: _Time;
    calcium: number;
    referenceId: [] | [bigint];
    nKgPerBed: number;
    notes: [] | [string];
    sulfur: number;
    magnesium: number;
    measurementType: _MeasurementType;
    location: [] | [string];
    nitrogen: number;
}): {
    cu: number;
    ec: number;
    fe: number;
    mn: number;
    oc: number;
    om: number;
    ph: number;
    zn: number;
    cec: number;
    kKgPerBed: number;
    soilType?: string;
    sodium: number;
    pKgPerBed: number;
    potassium: number;
    phosphorus: number;
    date: Time;
    calcium: number;
    referenceId?: bigint;
    nKgPerBed: number;
    notes?: string;
    sulfur: number;
    magnesium: number;
    measurementType: MeasurementType;
    location?: string;
    nitrogen: number;
} {
    return {
        cu: value.cu,
        ec: value.ec,
        fe: value.fe,
        mn: value.mn,
        oc: value.oc,
        om: value.om,
        ph: value.ph,
        zn: value.zn,
        cec: value.cec,
        kKgPerBed: value.kKgPerBed,
        soilType: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.soilType)),
        sodium: value.sodium,
        pKgPerBed: value.pKgPerBed,
        potassium: value.potassium,
        phosphorus: value.phosphorus,
        date: value.date,
        calcium: value.calcium,
        referenceId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.referenceId)),
        nKgPerBed: value.nKgPerBed,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes)),
        sulfur: value.sulfur,
        magnesium: value.magnesium,
        measurementType: from_candid_MeasurementType_n12(_uploadFile, _downloadFile, value.measurementType),
        location: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.location)),
        nitrogen: value.nitrogen
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    after: null;
} | {
    reference: null;
} | {
    before: null;
} | {
    daily: null;
}): MeasurementType {
    return "after" in value ? MeasurementType.after : "reference" in value ? MeasurementType.reference : "before" in value ? MeasurementType.before : "daily" in value ? MeasurementType.daily : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SoilMeasurement>): Array<SoilMeasurement> {
    return value.map((x)=>from_candid_SoilMeasurement_n8(_uploadFile, _downloadFile, x));
}
function to_candid_MeasurementType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MeasurementType): _MeasurementType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MeasurementType): {
    after: null;
} | {
    reference: null;
} | {
    before: null;
} | {
    daily: null;
} {
    return value == MeasurementType.after ? {
        after: null
    } : value == MeasurementType.reference ? {
        reference: null
    } : value == MeasurementType.before ? {
        before: null
    } : value == MeasurementType.daily ? {
        daily: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
